server {
    listen 443 ssl;
    listen [::]:443 ssl http2;

    server_name aizen-sousuke.duckdns.org www.aizen-sousuke.duckdns.org localhost;

    server_tokens off;
    root /usr/share/nginx/html;

    ssl_certificate /etc/letsencrypt/live/aizen-sousuke.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/aizen-sousuke.duckdns.org/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        try_files $uri /index.html;
    }

    # 精簡、允許 inline 和 eval 的 JS
    add_header Content-Security-Policy "
    default-src 'self' https: data:;
    script-src 'self' 'unsafe-inline' 'unsafe-eval' https:;
    img-src 'self' https: data: blob:;
    media-src 'self' https: blob: data:;
    " always;

}
